# Generated by Django 4.1.6 on 2023-11-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_visibility_alter_post_content_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Gdy zaznaczone - post będzie publiczny'),
        ),
    ]
